title: play-recaptcha
description: A Play Framework module that provides integration with Google reCAPTCHA.
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
